"""add user display name

Revision ID: bf093d91b73e
Revises: dc391e73f367
Create Date: 2026-08-15 16:03:32.279281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf093d91b73e'
down_revision = 'dc391e73f367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE users
            SET display_name = username
            WHERE display_name IS NULL
            """
        )
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
