"""add OAuth identities and public user identifiers

Revision ID: dc391e73f367
Revises: 9f3b1c7a2d4e
Create Date: 2026-08-14 16:24:41.526572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc391e73f367'
down_revision = '9f3b1c7a2d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identities_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_auth_identities_user_provider')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint('uq_users_public_id', ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    connection = op.get_bind()
    oauth_only_user_count = connection.execute(
        sa.text(
            "SELECT count(*) "
            "FROM users "
            "WHERE password_hash IS NULL"
        )
    ).scalar_one()

    linked_identity_count = connection.execute(
        sa.text("SELECT count(*) FROM auth_identities")
    ).scalar_one()

    if oauth_only_user_count or linked_identity_count:
        raise RuntimeError(
            "Cannot downgrade OAuth identities while OAuth-only users exist. "
            "Linked identities exist. Create a reviewed account migration plan first."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_public_id', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('token_version')
        batch_op.drop_column('public_id')

    op.drop_table('auth_identities')
    # ### end Alembic commands ###
